name: Kernel CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      # TODO: Get rid of this, only run upon pull requests
      - 71r1-github-actions
  pull_request:
    branches:
      - aosp/LA.UM.7.1.r1

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer
  kernel:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ix5/kernel-base
    steps:
      - uses: actions/checkout@v2
        with:
          path: common-kernel

      - name: Clone repos
        run: $GITHUB_WORKSPACE/common-kernel/clone-repos.sh

      - name: Move checked out repo to /srv/android
        run: mv $GITHUB_WORKSPACE/common-kernel/ /srv/android/kernel/sony/msm-4.14/common-kernel/

      - name: Run kernel CI script
        # TODO: Need a uses: or run: with entrypoint
        run: cd /srv/android/kernel/sony/msm-4.14/common-kernel/ && /bin/bash /srv/android/kernel/sony/msm-4.14/common-kernel/build-kernels-ci.sh

      - name: Archive logs
        uses: actions/upload-artifact@v2
        with:
          name: build-logs
          path: /srv/android/out/ci-clang/kernel-tmp/build_*.log

      # Only for testing: use the img from common-kernel instead
      #- name: Archive apollo kernel image from build dir
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: kernel-image-apollo
      #    path: /srv/android/out/ci-clang/kernel-tmp/arch/arm64/boot/Image.gz-dtb

      - name: Archive kernel images
        uses: actions/upload-artifact@v2
        with:
          name: kernel-images
          path: /srv/android/kernel/sony/msm-4.14/common-kernel/kernel-dtbo-*

      - name: Archive dtbos
        uses: actions/upload-artifact@v2
        with:
          name: kernel-dtbos
          path: /srv/android/kernel/sony/msm-4.14/common-kernel/dtbo-*.img
